### ISSUE TITLE
Problem with alfresco Mobile and alfresco 5.1.g

### ISSUE THREAD

**Issue by Manucciu** [jpotts/share-site-creators#26] opened 2016-09-26 14:50 UTC
Hello,

we got a error on alfresco mobile, with this add-on.

The app can t dowload the site : error failure to get the site on server.

Thank for your reply

**Comment by jpotts** [comment] 2016-09-26 17:51
So in an out-of-the-box 5.1.g install your mobile client works with Alfresco, but it stops working when you install this add-on?

**Comment by Manucciu** [comment] 2016-09-26 18:50
Exactly,

i have removed the repo amp, and just move the admin on site Creator and this work.

I think the problem is on the repo.

**Comment by jpotts** [comment] 2016-09-26 19:16
What version of Alfresco mobile and what OS?

**Comment by Manucciu** [comment] 2016-09-26 19:24
Alfresco mobile 2.3.1

Appel : iOS 9.3.1

**Comment by jpotts** [comment] 2016-09-29 14:55
Confirmed on 5.1.f (201604-GA). Thanks for reporting. Not sure what the problem is yet.

**Comment by jpotts** [comment] 2016-09-29 15:51
Actually this was already fixed in head. Can you pull the latest?

**Comment by jpotts** [comment] 2016-09-29 16:00
Created a new release 0.0.4 which includes this fix.

**Closed by jpotts** 2016-09-29 16:00 UTC

**Comment by Manucciu** [comment] 2016-09-29 17:11
That s work man, 

Thank you. 


De: "Jeff Potts" <notifications@github.com> 
À: "jpotts/share-site-creators" <share-site-creators@noreply.github.com> 
Cc: "Manucciu" <contact@dematco.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 29 Septembre 2016 18:00:35 
Objet: Re: [jpotts/share-site-creators] Problem with alfresco Mobile and alfresco 5.1.g (#26) 



Closed #26 . 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 



--
